/*
 * sdk_api_telemetry.h - Pure readback. Every function here just
 * copies fields out of the telemetry cache under its mutex - no
 * MAVLink traffic is generated by calling any of these.
 */
#ifndef SDK_API_TELEMETRY_H
#define SDK_API_TELEMETRY_H

#include <math.h>
#include <time.h>
#include "sdk_state.h"
#include "sdk_log.h"
#include "sdk_api_core.h"

static inline float get_roll(void)
{
    pthread_mutex_lock(&g_telem_lock);
    float v = g_telem.roll_rad * (180.0f / (float)M_PI);
    pthread_mutex_unlock(&g_telem_lock);
    return v;
}

static inline float get_pitch(void)
{
    pthread_mutex_lock(&g_telem_lock);
    float v = g_telem.pitch_rad * (180.0f / (float)M_PI);
    pthread_mutex_unlock(&g_telem_lock);
    return v;
}

static inline float get_yaw(void)
{
    pthread_mutex_lock(&g_telem_lock);
    float v = g_telem.yaw_rad * (180.0f / (float)M_PI);
    pthread_mutex_unlock(&g_telem_lock);
    return v;
}

/* get_heading()
 *   Compass heading 0-359 deg, from GLOBAL_POSITION_INT (falls back
 *   to attitude yaw if the autopilot hasn't reported a heading yet). */
static inline float get_heading(void)
{
    pthread_mutex_lock(&g_telem_lock);
    int16_t hdg_cdeg = g_telem.heading_cdeg;
    float yaw_deg = g_telem.yaw_rad * (180.0f / (float)M_PI);
    pthread_mutex_unlock(&g_telem_lock);

    if (hdg_cdeg >= 0) return hdg_cdeg / 100.0f;
    while (yaw_deg < 0.0f)   yaw_deg += 360.0f;
    while (yaw_deg >= 360.0f) yaw_deg -= 360.0f;
    return yaw_deg;
}

static inline double get_latitude(void)
{
    pthread_mutex_lock(&g_telem_lock);
    double v = g_telem.lat;
    pthread_mutex_unlock(&g_telem_lock);
    return v;
}

static inline double get_longitude(void)
{
    pthread_mutex_lock(&g_telem_lock);
    double v = g_telem.lon;
    pthread_mutex_unlock(&g_telem_lock);
    return v;
}

static inline gps_location_t get_location(void)
{
    gps_location_t loc;
    pthread_mutex_lock(&g_telem_lock);
    loc.lat        = g_telem.lat;
    loc.lon        = g_telem.lon;
    loc.alt_msl_m  = g_telem.alt_msl_m;
    loc.alt_rel_m  = g_telem.alt_rel_m;
    loc.valid      = g_telem.have_global_pos;
    pthread_mutex_unlock(&g_telem_lock);
    return loc;
}

static inline local_position_t get_local_position(void)
{
    pthread_mutex_lock(&g_telem_lock);
    local_position_t p = g_telem.local_pos;
    pthread_mutex_unlock(&g_telem_lock);
    return p;
}

static inline battery_status_t get_battery(void)
{
    pthread_mutex_lock(&g_telem_lock);
    battery_status_t b = g_telem.battery;
    pthread_mutex_unlock(&g_telem_lock);
    return b;
}

static inline float get_voltage(void)
{
    pthread_mutex_lock(&g_telem_lock);
    float v = g_telem.battery.voltage_v;
    pthread_mutex_unlock(&g_telem_lock);
    return v;
}

static inline int battery_remaining(void)
{
    pthread_mutex_lock(&g_telem_lock);
    int v = g_telem.battery.remaining_pct;
    pthread_mutex_unlock(&g_telem_lock);
    return v;
}

static inline int satellites(void)
{
    pthread_mutex_lock(&g_telem_lock);
    int v = g_telem.satellites_visible;
    pthread_mutex_unlock(&g_telem_lock);
    return v;
}

static inline gps_fix_t gps_fix(void)
{
    pthread_mutex_lock(&g_telem_lock);
    gps_fix_t v = g_telem.fix_type;
    pthread_mutex_unlock(&g_telem_lock);
    return v;
}

static inline bool ekf_ok(void)
{
    pthread_mutex_lock(&g_telem_lock);
    bool v = g_telem.ekf_ok;
    pthread_mutex_unlock(&g_telem_lock);
    return v;
}

/* heartbeat_ok()
 *   True if a HEARTBEAT arrived within the last 3 heartbeat periods -
 *   the same freshness window PX4 itself uses to judge link loss. */
static inline bool heartbeat_ok(void)
{
    pthread_mutex_lock(&g_telem_lock);
    bool have = g_telem.have_heartbeat;
    struct timespec last = g_telem.last_heartbeat;
    pthread_mutex_unlock(&g_telem_lock);
    if (!have) return false;

    struct timespec now;
    clock_gettime(CLOCK_MONOTONIC, &now);
    long age_ms = (now.tv_sec - last.tv_sec) * 1000L + (now.tv_nsec - last.tv_nsec) / 1000000L;
    return age_ms <= (3 * SDK_HEARTBEAT_PERIOD_MS);
}

static inline home_position_t get_home(void)
{
    pthread_mutex_lock(&g_telem_lock);
    home_position_t h = g_telem.home;
    pthread_mutex_unlock(&g_telem_lock);
    return h;
}

static inline system_status_t get_status(void)
{
    system_status_t s;
    pthread_mutex_lock(&g_telem_lock);
    s.armed          = g_telem.armed;
    s.ekf_ok         = g_telem.ekf_ok;
    s.mode           = sdk_px4_to_flight_mode(g_telem.custom_mode);
    s.system_status  = g_telem.system_status_raw;
    pthread_mutex_unlock(&g_telem_lock);
    s.heartbeat_ok   = heartbeat_ok();
    return s;
}

/* mission_time()
 *   Milliseconds since start(). */
static inline long mission_time(void)
{
    return sdk_now_ms_since_start();
}

/* flight_time()
 *   Milliseconds since the vehicle became armed. Returns 0 while
 *   disarmed (no dedicated "armed since" MAVLink message is cached,
 *   so this reads the same clock mission_time() does and is only
 *   meaningful once armed). */
static inline long flight_time(void)
{
    return is_armed() ? sdk_now_ms_since_start() : 0;
}

static inline rc_channels_t get_rc(void)
{
    pthread_mutex_lock(&g_telem_lock);
    rc_channels_t rc = g_telem.rc;
    pthread_mutex_unlock(&g_telem_lock);
    return rc;
}

/* link_quality()
 *   0-100 heuristic: 100 while heartbeat_ok(), 0 once it goes stale.
 *   MAVLink has no standard "signal quality" scalar over a wired/USB
 *   link, so this reflects link liveness rather than RF quality. */
static inline int link_quality(void)
{
    return heartbeat_ok() ? 100 : 0;
}

#endif /* SDK_API_TELEMETRY_H */
